"""initial

Revision ID: 03e940007b3d
Revises: 
Create Date: 2026-02-28 09:31:14.702565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e940007b3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zaliha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pn', sa.String(length=50), nullable=False),
    sa.Column('ime', sa.String(length=200), nullable=False),
    sa.Column('kolicina_platena', sa.Integer(), nullable=True),
    sa.Column('kolicina_neplatena', sa.Integer(), nullable=True),
    sa.Column('zabeleska', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zaliha')
    # ### end Alembic commands ###
